### ISSUE TITLE
[run the installer] TASK failing when attempting to spin up a 4 cluster

### ISSUE THREAD

**Issue by ibolton336** [fusor/mig-agnosticd#19]
```fatal: [clientvm.ibb0701ocp4b.internal]: FAILED! => {"ansible_job_id": "494777713481.17175", "changed": true, "cmd": ["openshift-install", "create", "cluster", "--dir=/home/ec2-user/cluster-ibb0701ocp4b"], "delta": "0:36:23.382917", "end": "2019-07-17 19:26:02.715785", "finished": 1, "msg": "non-zero return code", "rc": 1, "start": "2019-07-17 18:49:39.332868", "stderr": "level=info msg=\"Consuming \\\"Install Config\\\" from target directory\"\nlevel=info msg=\"Creating infrastructure resources...\"\nlevel=info msg=\"Waiting up to 30m0s for the Kubernetes API at https://api.cluster-ibb0701ocp4b.ibb0701ocp4b.mg.dog8code.com:6443...\"\nlevel=info msg=\"Make sure ssh-agent is running, env SSH_AUTH_SOCK is set to the ssh-agent's UNIX socket and your private key is added to the agent.\"\nlevel=info msg=\"Use the following commands to gather logs from the cluster\"\nlevel=info msg=\"ssh -A core@54.213.228.13 '/usr/local/bin/installer-gather.sh 10.0.134.215 10.0.146.232 10.0.161.111'\"\nlevel=info msg=\"scp core@54.213.228.13:~/log-bundle.tar.gz .\"\nlevel=fatal msg=\"waiting for Kubernetes API: context deadline exceeded\"", "stderr_lines": ["level=info msg=\"Consuming \\\"Install Config\\\" from target directory\"", "level=info msg=\"Creating infrastructure resources...\"", "level=info msg=\"Waiting up to 30m0s for the Kubernetes API at https://api.cluster-ibb0701ocp4b.ibb0701ocp4b.mg.dog8code.com:6443...\"", "level=info msg=\"Make sure ssh-agent is running, env SSH_AUTH_SOCK is set to the ssh-agent's UNIX socket and your private key is added to the agent.\"", "level=info msg=\"Use the following commands to gather logs from the cluster\"", "level=info msg=\"ssh -A core@54.213.228.13 '/usr/local/bin/installer-gather.sh 10.0.134.215 10.0.146.232 10.0.161.111'\"", "level=info msg=\"scp core@54.213.228.13:~/log-bundle.tar.gz .\"", "level=fatal msg=\"waiting for Kubernetes API: context deadline exceeded\""], "stdout": "", "stdout_lines": []}```

![image](https://user-images.githubusercontent.com/11218376/61409378-2467be80-a8b0-11e9-8a9d-435751346920.png)

**Comment by pranavgaikwad** [comment]
@ibolton336 can you please share the `.openshift_install.log` file on your `clientvm` instance. 

Connecting to `clientvm` instance : 
```
ssh -i <YOUR_OUTPUT_DIR>/agnostic_<YOUR_GUID>/<GUID>key
```

Once logged in, find `/home/ec2-user/cluster-<YOUR_GUID>/.openshift_install.log` file.

YOUR_GUID : `guid` variable from `my_vars.yml` file 
YOUR_OUTPUT_DIR: `output_dir` variable from `my_vars.yml` file

**Comment by ibolton336** [comment]
Sorry @pranavgaikwad I already ran the cleanup/destroy script

**Comment by pranavgaikwad** [comment]
This looks like an intermittent issue. He was able to launch the cluster the second time he tried. I'm keeping the issue open until further occurrence.

**Comment by jwmatthews** [comment]
A note that @Danil-Grigorev has been seeing this issue many times when he tries to use agnosticd for 4 envs.

**Comment by Danil-Grigorev** [comment]
This issue exists, and from initial observation, the issue is that the 4.x deployment does not create compute nodes. No matter which number of nodes is specified in configuration. Tried to deploy an ocp4 many times, (10+ at least with different OCP4 releases) and I'm not sure if I got any success at this point. Probably the problem is in the agnosticd itself, but the issue needs more attention, because some configurations now doesn't work as expected.

Same error message:

**Comment by dymurray** [comment]
I just want to add I have hit this problem 3 times in a row launching a 4.x cluster. The deadline exceeds and the openshift install logs do not provide any useful debugging information it appears.

**Comment by pranavgaikwad** [comment]
@Danil-Grigorev @dymurray please let me know if changing the `ocp4_token` solved the issue for you.

**Comment by pranavgaikwad** [comment]
**Identified Cause :** 
Wrong `ocp4_token` in `secret.yml` file leads to this issue. The OpenShift Installer downloads images from quay.io during installation. It uses the access token for quay.io present in `secret.yml` file. That token was either wrong or completely missing. This resulted in the Installer receiving "access denied" errors when trying to download images. This could be confirmed by gathering installer logs as specified in the last two lines of the error message. 

To generate installer logs, run this from `clientvm` instance : 
`ssh -A core@<ip> '/usr/local/bin/installer-gather.sh <ip1> <ip2> <ip3>'` 

Secondly, copy those logs to `clientvm` instance : 
`scp core@<ip>:~/log-bundle.tar.gz .`
 
See last three lines of error message to get the actual commands. 

Extract the log bundle, and read logs from `log-bundle/bootstrap/journals/bootkube.log` file. 
The error message in the log looks like this : 
```bash 
Jul 23 14:05:19 ip-10-0-15-218 bootkube.sh[1416]: unable to pull quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e63937b00e: unable to pull image: Error determining manifest MIME type for docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e63937b00e: Error reading manifest sha256:e63937b00e in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized
```
**Solution :**
Make sure you use the correct `ocp4_token` in secret.yml file. The token should look like this : 

```yaml
ocp4_token: '{"auths":{"cloud.openshift.com":{"auth":"<SOME_VALUE>","email":"john@doe.com"},"quay.io":{"auth":"<SOME_VALUE>","email":"john@doe.com"},"registry.connect.redhat.com":{"auth":"<SOME_OTHER_VALUE>","email":"john@doe.com"},"registry.redhat.io":{"auth":"<SOME_OTHER_VALUE>","email":"john@doe.com"}}}'
```

**Comment by Danil-Grigorev** [comment]
Updating the `pull-secret` from official page and replacing the full secret in configuration worked for me. Thanks @pranavgaikwad I would say that `secret.yml.example` is a bit misleading in this specification https://github.com/fusor/mig-agnosticd/blob/master/secret.yml.sample#L15 It would be better to change the line to `ocp4_token: 'REPLACE_WITH_PULL_SECRET'` to avoid confusion.

**Comment by pranavgaikwad** [comment]
@jwmatthews this issue can be closed now.
