### ISSUE TITLE
Velero not installing with workload

### ISSUE THREAD

**Issue by ibolton336** [fusor/mig-agnosticd#21]
./deploy_workload.sh -a create -w migration -v 3
did not install velero

**Comment by pranavgaikwad** [comment]
This issue can be attributed to a problem with the controller image. The operator launches Velero in `mig` namespace, old controller image would look for Velero in `velero` namespace. The namespace change was introduced in https://github.com/fusor/mig-controller/pull/185 which is now merged and is part of the controller image. 

This issue can be closed.
