### ISSUE TITLE
Update to deploy NooBaa by default and configure a MigStorage leveraging NooBaa

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-agnosticd#4]

**Comment by pranavgaikwad** [comment]
@jwmatthews Can you please elaborate on this? I am just trying to understand how NooBaa could be deployed. 
1. NooBaa deployment can be a part of agnosticd cluster deployment playbooks.
2. It can be a different workload.
3. It can be a part of `mig-agnosticd` in the form of an ansible playbook.

**Comment by pranavgaikwad** [comment]
@jwmatthews  After digging into and trying out NooBaa operator, here are some of my observations : 
1. We can launch NooBaa on one of the clusters using the operator.
2. We can get the connection details to the S3 endpoint exposed by NooBaa which we can use in migstorage. 
3. We _cannot_ add a storage resource in NooBaa using the operator. This is something user has to do from NooBaa web console.
